# Generated by Django 4.1.1 on 2022-11-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descirpcion', models.CharField(max_length=30)),
                ('costo_reposicion', models.BigIntegerField()),
                ('fehca_actualizacion', models.DateField()),
                ('id_categoria', models.BigIntegerField()),
            ],
            options={
                'db_table': 'articulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombrecompleto', models.TextField(blank=True, null=True)),
                ('rut', models.TextField(blank=True, null=True)),
                ('correo', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('updatedat', models.DateTimeField()),
                ('createdat', models.DateTimeField()),
            ],
            options={
                'db_table': 'base_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseZona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_zona', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_zona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depto', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=550)),
                ('valor_noche', models.BigIntegerField()),
                ('m2', models.BigIntegerField()),
                ('imagen_url', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.BigIntegerField()),
                ('q_banos', models.BigIntegerField()),
                ('q_plazas', models.BigIntegerField()),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetHuesped',
            fields=[
                ('id_dethues', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'det_huesped',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetInventario',
            fields=[
                ('id_det', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'det_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispServ',
            fields=[
                ('id_disp_serv', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'disp_serv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('tipo_empleado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncargadoProc',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'encargado_proc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GastoDepto',
            fields=[
                ('id_gasto', models.BigAutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor_pago', models.BigIntegerField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gasto_depto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id_huesped', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'huesped',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_depto', models.BigIntegerField()),
                ('fecha_actualiz', models.DateField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id_mp', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'medio_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoGasto',
            fields=[
                ('id_pg', models.BigAutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=30)),
                ('descirpcion', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_pago', models.DateField()),
                ('monto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pago_gasto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('f_checkin', models.DateField()),
                ('f_checkout', models.DateField()),
                ('valor_reserva', models.BigIntegerField()),
                ('valor_total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id_servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_tipo_serv', models.BigIntegerField()),
                ('tarifa', models.BigIntegerField()),
                ('fecha_pago', models.DateField()),
            ],
            options={
                'db_table': 'servicio_extra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProc',
            fields=[
                ('id_tipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_proc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoServ',
            fields=[
                ('id_tipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_serv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('contrasena', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'zona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetPg',
            fields=[
                ('id_reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.reserva')),
            ],
            options={
                'db_table': 'det_pg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetServicio',
            fields=[
                ('id_servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.servicioextra')),
            ],
            options={
                'db_table': 'det_servicio',
                'managed': False,
            },
        ),
    ]
